Cat.destroy_all

Cat.create!(content: 'http://i.imgur.com/6sKN51g.jpg')
Cat.create!(content: 'http://i.imgur.com/M3uAyJN.jpg')
Cat.create!(content: 'http://i.imgur.com/mjICQa7.jpg')
Cat.create!(content: 'http://i.imgur.com/qu32f4p.jpg')
Cat.create!(content: 'http://i.imgur.com/ras6wiQ.jpg')
Cat.create!(content: 'http://i.imgur.com/m4c73X2.jpg')
Cat.create!(content: 'http://i.imgur.com/7re5Vdt.jpg')
Cat.create!(content: 'http://i.imgur.com/2edajNf.jpg')
Cat.create!(content: 'http://i.imgur.com/FXuVKmO.jpg')
Cat.create!(content: 'http://i.imgur.com/lPq06xW.jpg')

Cat.create!(content: 'http://i.imgur.com/2yYDAEr.jpg')
Cat.create!(content: 'http://i.imgur.com/Sr09Ait.jpg')
Cat.create!(content: 'http://i.imgur.com/XD7hQyW.jpg')
Cat.create!(content: 'http://i.imgur.com/r7DypNz.jpg')
Cat.create!(content: 'http://i.imgur.com/22bINB2.jpg')
Cat.create!(content: 'http://i.imgur.com/3dgRYUI.jpg')
Cat.create!(content: 'http://i.imgur.com/FC2AmP7.jpg')
Cat.create!(content: 'http://i.imgur.com/wCI1w0q.jpg')
Cat.create!(content: 'http://i.imgur.com/i6AXc2I.jpg')
Cat.create!(content: 'http://i.imgur.com/YY1d52o.jpg')

Cat.create!(content: 'http://i.imgur.com/uesBHEj.jpg')
Cat.create!(content: 'http://i.imgur.com/Ju3ItzY.jpg')
Cat.create!(content: 'http://i.imgur.com/r8nmXqs.jpg')
Cat.create!(content: 'http://i.imgur.com/HAf0apW.jpg')
Cat.create!(content: 'http://i.imgur.com/I05qrqO.jpg')
Cat.create!(content: 'http://i.imgur.com/G4p5Oxt.jpg')
Cat.create!(content: 'http://i.imgur.com/NgQi1eh.jpg')
Cat.create!(content: 'http://i.imgur.com/TIW4ZqW.jpg')
Cat.create!(content: 'http://i.imgur.com/ORfgRjJ.jpg')
Cat.create!(content: 'http://i.imgur.com/itLNQ4r.jpg')

Cat.create!(content: 'http://i.imgur.com/1rxwk0t.jpg')
Cat.create!(content: 'http://i.imgur.com/0r36l2L.jpg')
Cat.create!(content: 'http://i.imgur.com/HfG1dtG.jpg')
Cat.create!(content: 'http://i.imgur.com/4ZpdL3s.jpg')
Cat.create!(content: 'http://i.imgur.com/lMenD8b.jpg')
Cat.create!(content: 'http://i.imgur.com/yoivtxl.jpg')
Cat.create!(content: 'http://i.imgur.com/ao5gdpM.jpg')
Cat.create!(content: 'http://i.imgur.com/hjAyKmu.jpg')
Cat.create!(content: 'http://i.imgur.com/c4PWCDb.jpg')
Cat.create!(content: 'http://i.imgur.com/Y8j5Jc0.jpg')

Cat.create!(content: 'http://i.imgur.com/KSx8KCg.jpg')
Cat.create!(content: 'http://i.imgur.com/V0M8REN.jpg')
Cat.create!(content: 'http://i.imgur.com/9SQjypR.jpg')
Cat.create!(content: 'http://i.imgur.com/o4glwRc.jpg')
Cat.create!(content: 'http://i.imgur.com/bYDrp7L.jpg')
Cat.create!(content: 'http://i.imgur.com/VJbgQn1.jpg')
Cat.create!(content: 'http://i.imgur.com/ku4T67r.jpg')
Cat.create!(content: 'http://i.imgur.com/qYpB3k9.jpg')
Cat.create!(content: 'http://i.imgur.com/Z21QBCN.jpg')
Cat.create!(content: 'http://i.imgur.com/TLL8ILc.jpg')

Cat.create!(content: 'http://i.imgur.com/i94L1iJ.jpg')
Cat.create!(content: 'http://i.imgur.com/kv4NR3m.jpg')
Cat.create!(content: 'http://i.imgur.com/Za2YbqR.jpg')
Cat.create!(content: 'http://i.imgur.com/XPocOIG.jpg')
Cat.create!(content: 'http://i.imgur.com/rSUzpzA.jpg')
Cat.create!(content: 'http://i.imgur.com/S4DPxfa.jpg')
Cat.create!(content: 'http://i.imgur.com/z1F0F6O.jpg')
Cat.create!(content: 'http://i.imgur.com/HJhnyeK.jpg')
Cat.create!(content: 'http://i.imgur.com/V1U24ce.jpg')
Cat.create!(content: 'http://i.imgur.com/j5TJVqu.jpg')

Cat.create!(content: 'http://i.imgur.com/cvrV7NP.jpg')
Cat.create!(content: 'http://i.imgur.com/zpxgmq2.jpg')
Cat.create!(content: 'http://i.imgur.com/mk84jvw.jpg')
Cat.create!(content: 'http://i.imgur.com/5UFXeb6.jpg')
Cat.create!(content: 'http://i.imgur.com/PQpjqyH.jpg')
Cat.create!(content: 'http://i.imgur.com/kqT401s.jpg')
Cat.create!(content: 'http://i.imgur.com/AvgAx0m.jpg')
Cat.create!(content: 'http://i.imgur.com/dsha3vs.jpg')
Cat.create!(content: 'http://i.imgur.com/QopB85u.jpg')
Cat.create!(content: 'http://i.imgur.com/B6bAJ2I.jpg')

Cat.create!(content: 'http://i.imgur.com/lB79MCe.jpg')
Cat.create!(content: 'http://i.imgur.com/ThsEZ7e.jpg')
Cat.create!(content: 'http://i.imgur.com/Xrz152k.jpg')
Cat.create!(content: 'http://i.imgur.com/iGF8qDH.jpg')
Cat.create!(content: 'http://i.imgur.com/8JlxAAu.jpg')
Cat.create!(content: 'http://i.imgur.com/3ZNcG5M.jpg')
Cat.create!(content: 'http://i.imgur.com/Qiuh7SB.jpg')
Cat.create!(content: 'http://i.imgur.com/mqnqsEX.jpg')
Cat.create!(content: 'http://i.imgur.com/hfIxxca.jpg')
Cat.create!(content: 'http://i.imgur.com/aNPNpCX.jpg')

Cat.create!(content: 'http://i.imgur.com/EJBPOp4.jpg')
Cat.create!(content: 'http://i.imgur.com/fzsTvEV.jpg')
Cat.create!(content: 'http://i.imgur.com/vGcooAz.jpg')
Cat.create!(content: 'http://i.imgur.com/zFlFzEm.jpg')
Cat.create!(content: 'http://i.imgur.com/4JMoX7A.jpg')
Cat.create!(content: 'http://i.imgur.com/CgIsExs.jpg')
Cat.create!(content: 'http://i.imgur.com/MnyVbAC.jpg')
Cat.create!(content: 'http://i.imgur.com/4hXQeww.jpg')
Cat.create!(content: 'http://i.imgur.com/qCcbItv.jpg')
Cat.create!(content: 'http://i.imgur.com/dGP9H8u.jpg')

Cat.create!(content: 'http://i.imgur.com/9ejk1Q6.jpg')
Cat.create!(content: 'http://i.imgur.com/8xgTFnk.jpg')
Cat.create!(content: 'http://i.imgur.com/algtggl.jpg')
Cat.create!(content: 'http://i.imgur.com/RANm8ir.jpg')
Cat.create!(content: 'http://i.imgur.com/P6qMe36.jpg')
Cat.create!(content: 'http://i.imgur.com/Co7r7vz.jpg')
Cat.create!(content: 'http://i.imgur.com/alY2xXH.jpg')
Cat.create!(content: 'http://i.imgur.com/CPcqJQE.jpg')
Cat.create!(content: 'http://i.imgur.com/FlPLcxE.jpg')
Cat.create!(content: 'http://i.imgur.com/DmSGavr.jpg')

Cat.create!(content: 'http://i.imgur.com/3KEGt4w.jpg')
Cat.create!(content: 'http://i.imgur.com/rOduSL9.jpg')
Cat.create!(content: 'http://i.imgur.com/EsaoBXB.jpg')
Cat.create!(content: 'http://i.imgur.com/F3L5fex.jpg')
Cat.create!(content: 'http://i.imgur.com/rErBnfh.jpg')
Cat.create!(content: 'http://i.imgur.com/l0z9xJg.jpg')
Cat.create!(content: 'http://i.imgur.com/kuzsqXB.jpg')
Cat.create!(content: 'http://i.imgur.com/nww1WHv.jpg')
Cat.create!(content: 'http://i.imgur.com/wcUUaZl.jpg')
Cat.create!(content: 'http://i.imgur.com/PnR0nxh.jpg')

Cat.create!(content: 'http://i.imgur.com/8YAWkSR.jpg')
Cat.create!(content: 'http://i.imgur.com/EBWLmqL.jpg')
Cat.create!(content: 'http://i.imgur.com/dheqndK.jpg')
Cat.create!(content: 'http://i.imgur.com/nQnkkFu.jpg')
Cat.create!(content: 'http://i.imgur.com/VTntN6x.jpg')
Cat.create!(content: 'http://i.imgur.com/5BD0J2R.jpg')
Cat.create!(content: 'http://i.imgur.com/08lqv6v.jpg')
Cat.create!(content: 'http://i.imgur.com/DwJZvX1.jpg')
Cat.create!(content: 'http://i.imgur.com/IWUpgI4.jpg')
Cat.create!(content: 'http://i.imgur.com/H0cJtcu.jpg')

Cat.create!(content: 'http://i.imgur.com/Bcfw7dh.jpg')
Cat.create!(content: 'http://i.imgur.com/QYYN1zE.jpg')
